# Default values for guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: Route

ingress:
  enabled: false

#frontend:
#  image_tag: openshift
