 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: guestbook
 spec:
   rules:
   - host: guestbook.patrocinio-iks-fa9ee67c9ab6a7791435450358e564cc-0000.us-east.containers.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: guestbook
           servicePort: 80
