 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: guestbook
 spec:
   rules:
   - http:
       paths:
       - path: /guestbook
         backend:
           serviceName: guestbook
           servicePort: 80
