apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      volumes:
        - name: data
          persistentvolumeclaim:
            claimName: mongodb-pvc
      containers:
      - name: mongodb
        image: mongo:latest
        volumeMounts:
          - name: data
            mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
