apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: messaging-service
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: messaging
    tier: messaging
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: messaging
      labels:
        app: messaging
        tier: messaging
    spec:
      # comment or delete the following line if you want to use a LoadBalancer
      type: ClusterIP
      # if your cluster supports it, uncomment the following to automatically create
      # an external load-balanced IP for the frontend service.
      # type: LoadBalancer
      ports:
      - port: 5672
      selector:
        app: messaging
        tier: messaging
