apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: messaging-deployment
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: messaging
    tier: messaging
spec:
  template:
    apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
    kind: Deployment
    metadata:
      name: messaging
    spec:
      selector:
        matchLabels:
          app: messaging
          role: master
          tier: messaging
      replicas: 1
      template:
        metadata:
          labels:
            app: messaging
            role: master
            tier: messaging
        spec:
          containers:
          - name: queue
            image: rabbitmq
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            ports:
            - containerPort: 5672
