apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mongo1-deployment
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: mongo1
spec:
  template:

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mongo1
    spec:
      selector:
        matchLabels:
          app: mongo1
      replicas: 1
      template:
        metadata:
          labels:
            app: mongo1
        spec:
          volumes:
            - name: mongo-data
              persistentVolumeClaim:
                claimName: mongo1-pvc
          terminationGracePeriodSeconds: 10
          containers:
          - name: mongo
            image: mongo
            command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
            ports:
            - containerPort: 27017
            volumeMounts:
            - name: mongo-data
              mountPath: /data/db
