apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mongo2-pvc
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: mongo2
spec:
  template:

    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: mongo2-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
