apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mongo1-service
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: mongo1
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: mongo1
      labels:
        app: mongo1
    spec:
      type: NodePort
      ports:
      - name: mongo
        port: 27017
        targetPort: 27017
        nodePort: 30017
      selector:
        app: mongo1
