apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: redis-master-service
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: redis
    tier: backend
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-master
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      ports:
      - port: 6379
        targetPort: 6379
      selector:
        app: redis
        role: master
        tier: backend
