apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: redis-slave-pvc
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: redis
    tier: backend
spec:
  template:
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: redis-slave-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
