apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: redis-cluster
  annotations:
#    app.ibm.com/is-local-deployable: "false"
  labels:
    app: redis
    tier: backend
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: redis-cluster
    data:
      redis.conf: |+
        cluster-enabled yes
        cluster-require-full-coverage no
        cluster-node-timeout 15000
        cluster-config-file /data/nodes.conf
        cluster-migration-barrier 1
        appendonly yes
        protected-mode no
