apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: application
  labels:
    app: guestbook
spec:
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
  selector:
    matchLabels:
      name: guestbook
