appInClusterNamespace: default

clusterReplicas: 1

placement:
  multicluster:
    enabled: true
    main:
      labelSelector:
        matchLabels:
          cloud: IBM
    redismaster:
      labelSelector:
        matchLabels:
          cloud: IBM

channel:
  name: gbchn
  namespace: gbchn
