apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: guestbook
    tier: backend
  name: backend
  namespace: guestbook-amine
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: backend
