apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: NodePort
  ports:
  - name: client
    port: 6379
    targetPort: 6379
    nodePort: 30380
  - name: gossip
    port: 16379
    targetPort: 16379
    nodePort: 31380
  selector:
    app: redis
    role: slave
    tier: backend
