apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - name: client
    port: 30379
    targetPort: 6379
    nodePort: 30379
  - name: gossip
    port: 31379
    targetPort: 16379
    nodePort: 31379
  selector:
    app: redis
    role: master
    tier: backend
